# Zurg configuration version
zurg: v1

token: YOUR_RD_API_TOKEN
host: "[::]" # do not change this if you are running it inside a docker container
port: 9999 # do not change this if you are running it inside a docker container
concurrent_workers: 40
check_for_changes_every_secs: 15 # check for new or deleted torrents
info_cache_time_hours: 12 # how long do we need to check for expired links?

enable_repair: true # BEWARE! THERE CAN ONLY BE 1 INSTANCE OF ZURG THAT SHOULD REPAIR YOUR TORRENTS
retain_folder_name_extension: false # if true, the folder name will contain the file extension when it is a torrent for a single file
on_library_update: | # use this to update your Plex library for example
  echo "hook"

network_buffer_size: 1048576 # 1 MiB
preferred_hosts: # Optional, run the script here https://github.com/debridmediamanager/real-debrid-network-test
  - 20.download.real-debrid.com
  - 21.download.real-debrid.com
  - 22.download.real-debrid.com
  - 23.download.real-debrid.com

# List of directory definitions and their filtering rules
directories:
  # Configuration for TV shows
  Serie:
    group: media # directories on different groups have duplicates of the same torrent
    group_order: 1
    filters:
      - regex: /season[\s\.]?\d/i          # Capture torrent names with the term 'season' in any case
      - regex: /saison[\s\.]?\d/i          # For non-English namings
      - regex: /stagione[\s\.]?\d/i        # if there's french, there should be italian too
      - regex: /s\d\d/i           # Capture common season notations like S01, S02, etc.
      - regex: /\btv/i            # anything that has TV in it is a TV show, right?
      - contains: complete
      - contains: seasons
      - any_file_inside_regex: /s\d\d/i
      - any_file_inside_regex: /\-\s\d\d\s\-/i
      - any_file_inside_regex: /episode.?\d{1,4}/i
      - any_file_inside_regex: /ep.?.?\d{1,4}/i

  # Configuration for movies
  Films:
    group: media # because movies and shows are in the same group,
    group_order: 2 # and shows has a lower group_order number than movies, all torrents that doesn't fall into shows will fall into movies
    filters:
      - regex: /.*/ # you cannot leave a directory without filters because it will not have any torrents in it
  torrents:
    group: all           # notice the group now is "all", which means it will have all the torrents of shows+movies combined because this directory is alone in this group
    filters:
      - regex: /.*/
