# Zurg configuration version
zurg: v1

token: YOUR_RD_API_TOKEN
port: 9999
concurrent_workers: 10
check_for_changes_every_secs: 15
info_cache_time_hours: 12
enable_repair: false # BEWARE! THERE CAN ONLY BE 1 INSTANCE OF ZURG THAT SHOULD REPAIR YOUR TORRENTS
on_library_update: |
  echo "You can execute anything here!" # https://github.com/debridmediamanager/zurg-testing/blob/main/config.md#library-update-trigger
network_buffer_size: 32768

# List of directory definitions and their filtering rules
directories:
  # Configuration for TV shows
  Series:
    group: media # directories on different groups have duplicates of the same torrent
    group_order: 1
    filters:
      - regex: /season[\s\.]?\d/i          # Capture torrent names with the term 'season' in any case
      - regex: /saison[\s\.]?\d/i          # For non-English namings
      - regex: /stagione[\s\.]?\d/i        # if there's french, there should be italian too
      - regex: /s\d\d/i           # Capture common season notations like S01, S02, etc.
      - regex: /\btv/i            # anything that has TV in it is a TV show, right?
      - contains: complete
      - contains: seasons
      - any_file_inside_regex: /s\d\d/i
      - any_file_inside_regex: /\d\s?x\s?\d\d/i

  # Configuration for movies
  Films:
    group: media # because movies and shows are in the same group,
    group_order: 2 # and shows has a lower group_order number than movies, all torrents that doesn't fall into shows will fall into movies
    filters:
      - regex: /.*/ # you cannot leave a directory without filters because it will not have any torrents in it

  torrents:
    group: all           # notice the group now is "all", which means it will have all the torrents of shows+movies combined because this directory is alone in this group
    filters:
      - regex: /.*/
