version: '3.9'
services:
  tor:
    image: debridmediamanager/tor
    container_name: tor
    deploy:
      replicas: 1
    networks:
      - mon-reseau

  dmm:
    image: debridmediamanager/debrid-media-manager:latest
    container_name: dmm
    env_file:
      - .env.local
    depends_on:
      - tor
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
