version: '3'

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - {{FOLDER_APP_SETTINGS}}/nginx-proxy-manager/data:/data
      - {{FOLDER_APP_SETTINGS}}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.2 # Adresse IP statique pour nginx-proxy-manager

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-ce
    restart: unless-stopped
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - {{FOLDER_APP_SETTINGS}}/portainer:/data
    ports:
      - 9000:9000
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.3 # Adresse IP statique pour portainer-ce

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM={{PLEX_CLAIM}}
      - TZ=Europe/Paris
    ports:
      - 32400:32400
    volumes:
      - {{FOLDER_APP_SETTINGS}}/plex/config:/config
      - {{FOLDER_APP_SETTINGS}}/plex/transcode:/transcode
      - {{FOLDER_RCLONE}}:/rclone
    restart: unless-stopped
    network_mode: bridge

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=latest
    volumes:
      - {{FOLDER_APP_SETTINGS}}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.5 # Adresse IP statique pour overseerr

  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - {{FOLDER_APP_SETTINGS}}/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.6 # Adresse IP statique pour tautulli

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris        
    volumes:
      - {{FOLDER_APP_SETTINGS}}/jackett/config:/config
      - {{FOLDER_APP_SETTINGS}}/jackett/blackhole/:/downloads   
    ports:
      - 9117:9117      
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.7 # Adresse IP statique pour jackett

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris 
    volumes:
      - {{FOLDER_APP_SETTINGS}}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.8 # Adresse IP statique pour prowlarr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true    
    environment:
      - TZ=Europe/Paris  
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}      
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}       
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.9 # Adresse IP statique pour flaresolverr

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Paris
    volumes:
      - {{FOLDER_APP_SETTINGS}}/wireguard/config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    #ports:
      #- 51820:51820/udp
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.10 # Adresse IP statique pour wireguard

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Europe/Paris"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"

networks:
  mon-reseau:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
