version: "3"

services:
  gluetun:
    image: ghcr.io/qdm12/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - {{APP_SETTINGS_DIR}}/gluetun:/gluetun
      # - OPENVPN_CUSTOM_CONFIG
    environment:
      - UID={{PUID}}
      - GID={{PGID}}
      - VPN_SERVICE_PROVIDER={{VPN_SERVICE_PROVIDER}}
      - VPN_TYPE={{VPN_TYPE}}
      # - OPENVPN_USER
      # - OPENVPN_PASSWORD
      # - VPN_ENDPOINT_IP
      # - VPN_ENDPOINT_PORT
      # - WIREGUARD_PUBLIC_KEY
      # - WIREGUARD_PRIVATE_KEY
      # - WIREGUARD_PRESHARED_KEY
      # - WIREGUARD_ADDRESSES
      # - CUSTOM_CONFIG
      - SERVER_COUNTRIES={{SERVER_COUNTRIES}}
      - TZ=Europe/Paris
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
