version: '3'

services:

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris 
    volumes:
      - {{APP_SETTINGS_DIR}}/heimdall:/config
      - {{USER_HOME}}:{{USER_HOME}}
    restart: unless-stopped
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
