version: '3'

services:

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
      - VERSION=latest
    volumes:
      - {{APP_SETTINGS_DIR}}/overseerr:/config
      - {{USER_HOME}}:{{USER_HOME}}
    restart: unless-stopped
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.5 # Adresse IP statique pour overseerr

networks:
  mon-reseau:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
