version: '3'

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-ce
    restart: unless-stopped
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - {{APP_SETTINGS_DIR}}/portainer:/data
      - {{USER_HOME}}:{{USER_HOME}}
    ports:
      - 9000:9000
    environment:
      - PUID={{PUID}}
      - PGID=101
      - TZ=Europe/Paris
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.4 # Adresse IP statique pour portainer-ce

networks:
  mon-reseau:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
