version: '3'

services:

  rdtclient:
    container_name: rdtclient
    volumes:
      - '{{USER_HOME}}/seedbox/local:/data/downloads'
      - '{{APP_SETTINGS_DIR}}/rdt-client:/data/db' 
      - '/mnt/zurg:/mnt/zurg'
    image: 'laster13/rdtclient:${TARGETPLATFORM}'
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.3 # Adresse IP statique pour radarr

networks:
  mon-reseau:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

