version: '3'

services:

  rdtclient:
    container_name: rdtclient
    volumes:
      - '{{USER_HOME}}/seedbox/local:/data/downloads'
      - '{{APP_SETTINGS_DIR}}/rdt-client:/data/db' 
      - /mnt:/mnt
    image: 'laster13/rdtclient:${TARGETPLATFORM}'
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge

