version: '3'

services:

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
    volumes:
      - {{APP_SETTINGS_DIR}}/tautulli:/config
      - {{USER_HOME}}:{{USER_HOME}}
    restart: unless-stopped
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
