version: '3'

services:

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
    volumes:
      - {{APP_SETTINGS_DIR}}/wireguard:/config
      - {{USER_HOME}}:{{USER_HOME}}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
