services:
  zurgrdt:
    image: ghcr.io/debridmediamanager/zurg-testing:v0-fuse
    container_name: zurgrdt
    restart: unless-stopped
    ports:
      - 9998:9998
    volumes:
      - {{APP_SETTINGS_DIR}}/zurgrdt/config.yml:/app/config.yml
      - zurgrdt:/app/data
      - /mnt/zurgrdt:/app/mnt:shared
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    command: mount -o attr_timeout=1.0 -o allow_other -o uid=1000 -o gid=1000 -o fsname=myawesomemount -o subtype=zurg -o atomic_o_trunc -o max_readahead=131072 -o default_permissions -o ro
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge

volumes:
  zurgrdt: