services:
  zurgrclone:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: zurgrclone
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - {{APP_SETTINGS_DIR}}/zurgrclone/config.yml:/app/config.yml
      - zurgdata:/app/data
    networks:
      - mon-reseau

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - PUID={{PUID}}
      - PGID={{PGID}}
    volumes:
      - /mnt/zurgrclone:/data:rshared
      - {{USER_HOME}}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurgrclone
    command: "mount zurg: /data --allow-non-empty --allow-other --uid={{PUID}} --gid={{PGID}} --dir-cache-time 10s --vfs-cache-mode full"
    networks:
      - mon-reseau

  zurgfuse:
    image: ghcr.io/debridmediamanager/zurg-testing:v0-fuse
    container_name: zurgfuse
    restart: unless-stopped
    ports:
      - 9998:9998
    volumes:
      - {{APP_SETTINGS_DIR}}/zurgfuse/config.yml:/app/config.yml
      - zurgdata2:/app/data
      - /mnt/zurgfuse:/app/mnt:shared
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    command: mount -o attr_timeout=1.0 -o allow_other -o uid=1000 -o gid=1000 -o fsname=myawesomemount -o subtype=zurg -o atomic_o_trunc -o max_readahead=131072 -o default_permissions -o ro
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge

volumes:
  zurgdata:
  zurgdata2: